#!/usr/bin/env bash

macos_defaults_presets=(minimal developer privacy)
macos_defaults_toggles=(
  key_repeat
  finder_power_user
  dock_autohide
  screenshots_desktop
  activity_monitor
  privacy_baseline
)

macos_defaults_preset_description() {
  case "$1" in
    minimal)
      echo "Minimal: conservative Finder, dialog, and screenshot defaults."
      ;;
    developer)
      echo "Developer: minimal defaults plus fast keyboard, power-user Finder, Dock, and Activity Monitor settings."
      ;;
    privacy)
      echo "Privacy: minimal defaults plus reduced ad personalization and web search leakage."
      ;;
    *)
      return 1
      ;;
  esac
}

macos_defaults_toggle_description() {
  case "$1" in
    key_repeat)
      echo "Fast keyboard repeat and disable press-and-hold accents"
      ;;
    finder_power_user)
      echo "Show hidden files, path/status bars, list view, and suppress extension warnings"
      ;;
    dock_autohide)
      echo "Auto-hide Dock with no delay and hide recent apps"
      ;;
    screenshots_desktop)
      echo "Save PNG screenshots to Desktop without window shadows"
      ;;
    activity_monitor)
      echo "Open Activity Monitor main window and show all processes"
      ;;
    privacy_baseline)
      echo "Disable Apple personalized ads and Safari search suggestions"
      ;;
    *)
      return 1
      ;;
  esac
}

macos_defaults_preset_toggles() {
  case "$1" in
    minimal)
      echo "screenshots_desktop"
      ;;
    developer)
      echo "key_repeat finder_power_user dock_autohide screenshots_desktop activity_monitor"
      ;;
    privacy)
      echo "finder_power_user screenshots_desktop privacy_baseline"
      ;;
    *)
      return 1
      ;;
  esac
}

macos_defaults_is_noninteractive() {
  [[ "${CI:-}" == "true" || "${NONINTERACTIVE:-}" == "1" || ! -t 0 ]]
}

macos_defaults_has_toggle() {
  local needle="$1"
  shift
  local toggle
  for toggle in "$@"; do
    [[ "$toggle" == "$needle" ]] && return 0
  done
  return 1
}

macos_defaults_prompt_yes_no() {
  local prompt="$1"
  local default_answer="$2"
  local answer
  local suffix

  if [[ "$default_answer" == "yes" ]]; then
    suffix="Y/n"
  else
    suffix="y/N"
  fi

  while true; do
    read -r -p "${prompt} [${suffix}] " answer
    answer="${answer:-$default_answer}"
    case "$answer" in
      y|Y|yes|YES|Yes) return 0 ;;
      n|N|no|NO|No) return 1 ;;
      *) echo "Please answer yes or no." >&2 ;;
    esac
  done
}

macos_defaults_select_preset() {
  local selected="${1:-}"
  local index preset

  if [[ -n "$selected" ]]; then
    for preset in "${macos_defaults_presets[@]}"; do
      if [[ "$selected" == "$preset" ]]; then
        echo "$selected"
        return 0
      fi
    done
    echo "Unknown macOS defaults preset: ${selected}" >&2
    return 1
  fi

  if macos_defaults_is_noninteractive; then
    echo "minimal"
    return 0
  fi

  echo "Choose a macOS defaults preset:" >&2
  index=1
  for preset in "${macos_defaults_presets[@]}"; do
    echo "  ${index}) $(macos_defaults_preset_description "$preset")" >&2
    index=$((index + 1))
  done

  while true; do
    read -r -p "Preset [2]: " selected
    selected="${selected:-2}"
    case "$selected" in
      1|minimal) echo "minimal"; return 0 ;;
      2|developer) echo "developer"; return 0 ;;
      3|privacy) echo "privacy"; return 0 ;;
      *) echo "Please choose 1, 2, or 3." >&2 ;;
    esac
  done
}

macos_defaults_select_toggles() {
  local preset="$1"
  shift || true
  local explicit_toggles=("$@")
  local selected_toggles=()
  local preset_toggles toggle default_answer

  if ((${#explicit_toggles[@]} > 0)); then
    printf '%s\n' "${explicit_toggles[@]}"
    return 0
  fi

  read -r -a preset_toggles <<<"$(macos_defaults_preset_toggles "$preset")"

  if macos_defaults_is_noninteractive; then
    printf '%s\n' "${preset_toggles[@]}"
    return 0
  fi

  echo "" >&2
  echo "Customize individual settings:" >&2
  for toggle in "${macos_defaults_toggles[@]}"; do
    if macos_defaults_has_toggle "$toggle" "${preset_toggles[@]}"; then
      default_answer="yes"
    else
      default_answer="no"
    fi

    if macos_defaults_prompt_yes_no "$(macos_defaults_toggle_description "$toggle")" "$default_answer"; then
      selected_toggles+=("$toggle")
    fi
  done

  printf '%s\n' "${selected_toggles[@]}"
}

macos_defaults_render_script() {
  local preset="$1"
  shift
  local toggles=("$@")
  local toggle

  cat <<DEFAULTS
#!/usr/bin/env bash
set -euo pipefail

# macOS system preferences generated by machete defaults --init.
# Preset: ${preset}
# Re-run safely via: ./machete defaults

# --- Dialogs ---
defaults write -g NSNavPanelExpandedStateForSaveMode -bool true
defaults write -g NSNavPanelExpandedStateForSaveMode2 -bool true
defaults write -g PMPrintingExpandedStateForPrint -bool true
defaults write -g PMPrintingExpandedStateForPrint2 -bool true

# --- Finder ---
defaults write NSGlobalDomain AppleShowAllExtensions -bool true
DEFAULTS

  for toggle in "${toggles[@]}"; do
    case "$toggle" in
      key_repeat)
        cat <<'DEFAULTS'

# --- Keyboard ---
defaults write -g ApplePressAndHoldEnabled -bool false
defaults write NSGlobalDomain KeyRepeat -int 2
defaults write NSGlobalDomain InitialKeyRepeat -int 15
DEFAULTS
        ;;
      finder_power_user)
        cat <<'DEFAULTS'
defaults write com.apple.finder AppleShowAllFiles -bool true
defaults write com.apple.finder ShowPathbar -bool true
defaults write com.apple.finder ShowStatusBar -bool true
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
DEFAULTS
        ;;
      dock_autohide)
        cat <<'DEFAULTS'

# --- Dock ---
defaults write com.apple.dock autohide -bool true
defaults write com.apple.dock autohide-delay -float 0
defaults write com.apple.dock autohide-time-modifier -float 0.3
defaults write com.apple.dock show-recents -bool false
DEFAULTS
        ;;
      screenshots_desktop)
        cat <<'DEFAULTS'

# --- Screenshots ---
defaults write com.apple.screencapture location -string "${HOME}/Desktop"
defaults write com.apple.screencapture type -string "png"
defaults write com.apple.screencapture disable-shadow -bool true
DEFAULTS
        ;;
      activity_monitor)
        cat <<'DEFAULTS'

# --- Activity Monitor ---
defaults write com.apple.ActivityMonitor OpenMainWindow -bool true
defaults write com.apple.ActivityMonitor ShowCategory -int 0
DEFAULTS
        ;;
      privacy_baseline)
        cat <<'DEFAULTS'

# --- Privacy ---
defaults write com.apple.AdLib allowApplePersonalizedAdvertising -bool false
defaults write com.apple.Safari UniversalSearchEnabled -bool false
defaults write com.apple.Safari SuppressSearchSuggestions -bool true
DEFAULTS
        ;;
      *)
        echo "Unknown macOS defaults toggle: ${toggle}" >&2
        return 1
        ;;
    esac
  done

  cat <<'DEFAULTS'

# --- Apply ---
killall Dock Finder SystemUIServer 2>/dev/null || true
echo "  - macOS defaults applied"
DEFAULTS
}

macos_defaults_init() {
  local destination_file="$1"
  local preset="${2:-}"
  if (($# >= 2)); then
    shift 2
  else
    shift
  fi
  local toggles=()

  preset="$(macos_defaults_select_preset "$preset")"
  while IFS= read -r toggle; do
    [[ -n "$toggle" ]] && toggles+=("$toggle")
  done < <(macos_defaults_select_toggles "$preset" "$@")

  mkdir -p "$(dirname "$destination_file")"
  macos_defaults_render_script "$preset" "${toggles[@]}" > "$destination_file"
  chmod +x "$destination_file"
  echo "  - Created ${destination_file} from the ${preset} preset"
}
